export const KEY = '93de00cc840954b1b665c0239301b34e';
export const KEY2 = '5bc45d6b14275a0b629004f6ab5109f7';
const IP_LOCATION_SERVICE_KEY = 'ad2efd6d679b54';
export const MAIN_LINK = 'https://api.openweathermap.org/data/2.5/';
export const FLAG_LINK = 'https://lipis.github.io/flag-icon-css/flags/4x3/';
export const IP_LOC = `https://ipinfo.io/json?token=${IP_LOCATION_SERVICE_KEY}`;
export const ICON_LINK = '/assets/';
export const ASSETS = '../assets/';
export const PROD_ASSETS = '/Weather/assets';
export const PROD_ICON_LINK = '/Weather/assets/icons-png';
export const UNITS = 'metric';
